print("Selamat datang pada form registrasi pendaftaran sekolah A\n")
print("===========================================================")
print("Silahkan isi form dibawah ini: ")
nama = input("Masukan nama anda: ")
usia = input("Masukan usia anda: ")
hobi = input("Masukan hobi anda: ")
alamat = input("Masukan alamat anda: ")
nilai1 = input("Masukan nilai bahasa indonesia: ")
nilai2 = input("Masukan nilai matematika: ")
nilai3 = input("Masukan nilai IPS: ")
nilai4 = input("Masukan nilai IPA: ")
penjumlahan_nilai = int(nilai1) + int(nilai2) + int(nilai3) + int(nilai4)

print("Berikut data anda..\n")
print(f"Nama anda adalah {nama}, anda berusia {usia} tahun, anda berasal dari {alamat}.\n")
print(f"Anda memiliki hobi yang bagus, hobi anda adalah {hobi}")
print(f"Kami telah mendapatkan nilai anda yaitu Bahasa Indonesia {nilai1}, Matematika {nilai2}, IPS {nilai3}, dan IPA {nilai4}")
print(f"Berikut penjumlahan nilai anda: {penjumlahan_nilai}")
