print("Cobalah kalkulator sederhana ini")
angka1 = input("Masukkan pertama: ")
angka2 = input("Masukkan kedua: ")
angka3 = input("Masukkan ketiga: ")
angka4 = input("Masukkan keempat: ")

penjumlahan = int(angka1) + int(angka2) + int(angka3) + int(angka4)
pengurangan = int(angka1) - int(angka2) - int(angka3) - int(angka4)
pembagian = int(angka1) / int(angka2) / int(angka3) / int(angka4)
perkalian = int(angka1) * int(angka2) * int(angka3) * int(angka4)

print("======SEDANG DI PROSES=====")
print("Berikut adalah jawabannya")
print(f"Untuk jawaban dari {angka1} + {angka2} + {angka3} + {angka4} = {penjumlahan}")
print(f"Untuk jawaban dari {angka1} - {angka2} - {angka3} - {angka4} = {pengurangan}")
print(f"Untuk jawaban dari {angka1} / {angka2} / {angka3} / {angka4} = {pembagian}")
print(f"Untuk jawaban dari {angka1} * {angka2} * {angka3} * {angka4} = {perkalian}")